### ISSUE TITLE
BreakPoints에 더 작은 xs같은게 있으면 좋을 것 같습니다

### ISSUE THREAD

**Issue by lonyele** [pedaling/class101-ui#185]
## Problem
현재 가장 작은 BreakPoints는 sm인 1023인데 더 작은뷰에서 특정하게 뭔갈 하고 싶은데 할 수가 없네요. 나중에 다들 같이 한번 모여서 제대로 논의하면 좋을것 같지만 현재로선 작은거 하나만 추가가 되면은 다른 기능 추가에 문제는 없을 것 같습니다

## Possible Solution
일단 대충 유명 UI라이브러리 뒤져보자면 이런식인데. 그냥 지금 대충 적당해 보이는거 576으로 넣었는데 한번 논의 해볼까요? 전부 바꾸거나 아키텍쳐를 mobile-first식으로 바꾼다거나 하는건 좀 무리가 있으니까...  적당한 정도로만요

##### [Bootstrap 4](https://getbootstrap.com/docs/4.0/layout/overview/)
```
// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

##### [Material UI](https://material-ui.com/customization/breakpoints/)
```
xs, extra-small: 0px
sm, small: 600px
md, medium: 960px
lg, large: 1280px
xl, extra-large: 1920px
```

##### [Ant Design](https://ant.design/components/grid/#Col)
```
xs | <576px 
sm | ≥576px
md | ≥768px
lg | ≥992px
xl | ≥1200px
xxl | ≥1600px
```

##### [Semantic UI](https://semantic-ui.com/elements/container.html)
```
below 768px 
768px - 991px
992px - 1200px 
above 1200px
```

##### [Fabric UI](https://developer.microsoft.com/en-us/fabric#/styles/web/layout)
```
small | 320px - 479px
medium | 480px - 639px
large | 640px - 1023px
extra large | 1024px - 1365px
exta extra large | 1366px - 1919px
extra extra extra large | 1920px and up
```

**Comment by bae-unidev** [comment]
우리가 지금 phones, tablets, desktops 순서로 sm, md, lg인데 xs는 어느 기기 류에 대응되게 되는걸까?

**Comment by lonyele** [comment]
아, 코드상을 봤을때는 요렇게인데 일반적으로 md급(타블렛)에 600~1000 정도가 있고  600이하가 모바일인 느낌이 있어서 그랬어. 그래서 sm이 이미 1023이어서 xs추가를 말한거입니다. sm이나 md를 수정/추가 하는거는 전체 코드적으로 바꿔야 되는게 너무 많아서. 근데 방금 또 쿤하고 얘기해본결과 현재는 그렇게 딱히 필요 없을것 같아
``` 
export const SIZES = {
  sm: { maxWidth: 1023 },
  md: {}, // TODO: 태블릿 사이즈가 추가되면 수정합니다.
  lg: { minWidth: 1024 },
}
```

**Comment by lonyele** [comment]
이거 oui에서 새로 고고 @chiabi   from 처리가
