### ISSUE TITLE
message 요소의 높이를 고려하여 Input 컴포넌트의 높이를 설계했으면 좋겠습니다

### ISSUE THREAD

**Issue by mu-hun** [pedaling/class101-ui#250]
**Is your feature request related to a problem? Please describe.**

| N/A | message |
| :-: | :-: |
|<img width="469" alt="Screen Shot 2020-05-16 at 8 43 46 PM" src="https://user-images.githubusercontent.com/5278201/82120040-4b3b9d80-97be-11ea-9303-39b009c406da.png"> | <img width="469" alt="Screen Shot 2020-05-16 at 8 43 16 PM" src="https://user-images.githubusercontent.com/5278201/82120043-4f67bb00-97be-11ea-9703-e2c95676ce00.png"> |
| 48px | 66px |

안녕하세요. [클래스 101 로그인 페이지](https://class101.net/login)의 입력 컨테이너의 유효성 검사 결과 이전과 이후의 높이의 차이를 없게 설계를 한다면 보다 덜 끊기는 인터렉션을 경험할 것 같아 이슈로 의견을 남깁니다.

**Describe the solution you'd like**

```tsx
{!(allowMessage || errorMessage || warnMessage) && <DummyError>Dummy</DummyError>}

const DummyError = styled.h6`
  line-height: 16px;
  font-size: 11px;
  margin: 2px 0;
`;
```

`<InlineError />` 명세와 동일한 높이의 더미 컴포넌트 <DummyError/>를 만들어 주입하면 될 것 같습니다.

**Comment by chiabi** [comment]
@x86chi 님 저희 프로젝트에 관심 가져주시고 의견 주셔서 감사합니다!

현재 폼 관련 컴포넌트들이 통일성 있게 개발되지 않아서, 메시지 / 라벨을 관리하는 컴포넌트와 인풋을 분리한 방향으로 개선할 예정입니다.
다만, 해당 컴포넌트를 바로 개선하기에는 서비스 내부에서 이미 많이 사용하고 있어서
서비스 내부에서 별도로 개발하여 점진적으로 변경 후, 해당 프로젝트에도 반영될 예정입니다.
(해당 개선 방향은 #124 을 참고합니다)

의견 주신 더미 에러의 경우, 위아래 인풋 간에 에러가 노출되는 영역을 고려한 고정된 간격이 필요하므로 해당 내용에 관해서 디자이너와 함께 개선할 예정입니다.

다시 한 번 소중한 의견에 감사드립니다.
