### ISSUE TITLE
Switch off/onText prop 이름 변경하기

### ISSUE THREAD

**Issue by bae-unidev** [pedaling/class101-ui#99]
Component도 받을 수 있는데 Text인거 좀 이상한것 같애

**Comment by tbvjaos510** [comment]
component도 어떻게 보면 text를 위한 컴포넌트를 작성하는 거라서 텍스트가 낫지 않을까? 더 자연스러운 이름 있으면 추천해줘!

**Comment by bae-unidev** [comment]
사실 on/off 할때마다 텍스트가 바뀌면 사람들이 햇갈려하는 경우가 많아! 이게 현재 상태인가? 누르면 저렇게 바뀐다는건가? 이렇게 생각하면 엄청 햇갈려 ㅋㅋ
추가로 https://blueprintjs.com/docs/#core/components/switch 참고하면 그냥 labelElement라고 쓰긴 하는데, 우린 조금 더 확장해서 `labelComponent: (checked: boolean) => React.ReactNode | React.ReactNode` 라고 하면 혹여나 바뀌는 경우두 충분히 커버 가능할 것 같애!

**Comment by tbvjaos510** [comment]
오케이 on/off부분은 디자인 시안 보고 만든거라서 쿤이랑 이야기해보고 labelComponent로 수정할게
